services:
  app-1:
    build: .
    command: sh -c './wait-for redis:6379 -- ./cat'
    depends_on:
      - mongo
      - redis
    ports:
      - "8081:8081"
    container_name: app-1
  app-2:
    build: .
    command: sh -c './wait-for redis:6379 -- ./cat'
    depends_on:
      - mongo
      - redis
    ports: 
      - "8082:8081"
    container_name: app-2
  mongo: 
    image: mongo
    ports: 
      - "27017:27017"
    container_name: mongo

  redis:
    image: redis
    depends_on:
      - mongo
    ports: 
      - "6379:6379"
    container_name: redis

  kafka:
    image: spotify/kafka
    depends_on:
      - redis
    ports:
    - "9092:9092"
    - "2181:2181"
    hostname: kafka
    container_name: kafka
    environment: 
      - "ADVERTISED_PORT=9092"
      - "AUTO_CREATE_TOPICS=true"



networks:
  cat-service-mongo:
    driver: bridge